<br><h1><label>Biblioteca de álbuns</label></h1>
<hr id="hr"/>

<!--<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Editar Álbum ID = <?php //echo $this->id; ?>        
        </div>
    </div>
    <form class="form-horizontal" role="form" method="POST" action="<?php //echo $this->url('albuns', array('action' => 'atualizar')); ?>">
        <div class="panel-body">
            <div class="form-group">
                <label for="inputArtista" class="col-lg-3 col-md-3 control-label">Nome:</label>
                <div class="col-lg-9 col-md-9">
                    <input type="text" name="artista" class="form-control" id="inputNome" placeholder="Artista" value="<?//php echo $this->form['artista']; ?>">
                </div>
            </div>
 
            <div class="form-group">
                <label for="inputTitulo" class="col-lg-3 col-md-3 control-label">Titulo:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="titulo" class="form-control" id="inputTelefonePrincipal" placeholder="Título" value="<?php //echo $this->form['titulo']; ?>">
                </div>
            </div>
 
            <div class="form-group">
                <label for="inputGenero" class="col-lg-3 col-md-3 control-label">Gênero:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="genero" class="form-control" id="inputTelefoneSecundario" placeholder="Gênero" value="<?php echo $this->form['genero']; ?>">
                </div>
            </div>
            
            <div class="form-group">
                <label for="inputAno" class="col-lg-3 col-md-3 control-label">Ano:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="ano" class="form-control" id="inputTelefoneSecundario" placeholder="Ano" value="<?php echo $this->form['ano']; ?>">
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <input type="hidden" name="id" value="<?php //echo $this->id; ?>">
            <button type="submit" class="btn btn-primary">Atualizar álbum</button>
            <a href="<?php //echo $this->url('albuns'); ?>" class="btn btn-default">Voltar</a>
        </div>
    </form>
</div>-->

 

<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Editar álbum ID = <?php echo $this->id; ?>        
        </div>
    </div>
    <?php
    // objeto form contato
    $formAlbum = $this->formAlbum;
    // preparar elementos do formulário
    $formAlbum->prepare();
    // configurar url formulário
    $formAlbum->setAttribute('action', $this->url('albuns', array('action' => 'atualizar')));
    ?>
    
    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formAlbum) ?>
    <div class="panel-body">
        <div class="form-group">
            <label for="inputNome" class="col-lg-3 col-md-3 control-label">Artista:</label>
            <div class="col-lg-9 col-md-9">
                <?php 
                // renderiza html input
                echo $this->formInput($formAlbum->get('artista'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formAlbum->get('artista'));
                ?>
            </div>
        </div>
 
        <br><div class="form-group">
            <label for="inputTelefonePrincipal" class="col-lg-3 col-md-3 control-label">Título:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formAlbum->get('titulo'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formAlbum->get('titulo'));
                ?>
            </div>
        </div>
 
        <br><div class="form-group">
            <label for="inputTelefoneSecundario" class="col-lg-3 col-md-3 control-label">Gênero:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formAlbum->get('genero'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formAlbum->get('genero'));
                ?>
            </div>
        </div>
 
        <br><div class="form-group">
            <label for="inputTelefoneSecundario" class="col-lg-3 col-md-3 control-label">Ano:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formAlbum->get('ano'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formAlbum->get('ano'));
                ?>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        //echo $this->formHidden($formAlbum->get('id'));
        // renderiza html input hidden csrf
        //echo $this->formElement($formContato->get('security')); 
        ?>
 
        <button type="submit" class="btn btn-primary">Atualizar álbum</button>
        <a href="<?php echo $this->url('albuns'); ?>" class="btn btn-default">Voltar</a>
    </div>
 
    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>