<br><h1><label>Biblioteca de álbuns</label></h1>
<hr id="hr"/>

<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Editar Álbum ID = <?php echo $this->id; ?>        
        </div>
    </div>
    <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('albuns', array('action' => 'atualizar')); ?>">
        <div class="panel-body">
            <div class="form-group">
                <label for="inputArtista" class="col-lg-3 col-md-3 control-label">Nome:</label>
                <div class="col-lg-9 col-md-9">
                    <input type="text" name="artista" class="form-control" id="inputNome" placeholder="Nome Completo" value="<?php echo $this->form['artista']; ?>">
                </div>
            </div>
 
            <div class="form-group">
                <label for="inputTitulo" class="col-lg-3 col-md-3 control-label">Titulo:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="titulo" class="form-control" id="inputTelefonePrincipal" placeholder="Digite seu telefone principal" value="<?php echo $this->form['titulo']; ?>">
                </div>
            </div>
 
            <div class="form-group">
                <label for="inputGenero" class="col-lg-3 col-md-3 control-label">Gênero:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="genero" class="form-control" id="inputTelefoneSecundario" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->form['genero']; ?>">
                </div>
            </div>
            
            <div class="form-group">
                <label for="inputAno" class="col-lg-3 col-md-3 control-label">Ano:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="ano" class="form-control" id="inputTelefoneSecundario" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->form['ano']; ?>">
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>">
            <button type="submit" class="btn btn-primary">Atualizar álbum</button>
            <a href="<?php echo $this->url('albuns'); ?>" class="btn btn-default">Voltar</a>
        </div>
    </form>
</div>