<br><h1><label>Biblioteca de álbuns</label></h1>
<hr id="hr"/>

<a href="<?php echo $this->url('albuns', array('action' => 'novo'))?>">
    <button id="btn-new" class="btn btn-primary" type="button">+ Novo álbum</button>
</a>

<form class="form-inline" id="float-r" role="form">
  <div class="form-group">
    <label for="inputEmail3" class="sr-only"></label>
    <input type="email" class="form-control" id="inputPassword2" placeholder="Busca...">
  </div>
  <button type="submit" class="btn btn-default">Procurar</button>
</form>

<table class="table">
    <thead><tr><th colspan="6"></th></tr></thead>
    <thead>
        <tr>
            <th>#</th>
            <th>Artista</th>
            <th>Álbum</th>
            <th>Gênero</th>
            <th>Ano</th>
            <th>Ação</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>1</td>
            <td>U2</td>
            <td>Songs of Innocense</td>
            <td>Rock</td>
            <td>2014</td>
            <td>
                <a class="btn btn-xs btn-info" title="Visualizar" href="<?php echo $this->url('albuns', array("action" => "detalhes", "id" => 85,)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('albuns', array("action" => "editar", "id" => 85,)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('albuns', array("action" => "deletar", "id" => 85,)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
            </td>
        </tr>

        <tr>
            <td>2</td>
            <td>David Guetta</td>
            <td>Listen (Deluxe Edition)</td>
            <td>Dance, House, Eletrônica</td>
            <td>2014</td>
            <td>
                <a class="btn btn-xs btn-info" title="Visualizar" href="<?php echo $this->url('albuns', array("action" => "detalhes", "id" => 85,)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('albuns', array("action" => "editar", "id" => 85,)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('albuns', array("action" => "deletar", "id" => 85,)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
            </td>
        </tr>

        <tr>
            <td>3</td>
            <td>Olly Murs</td>
            <td>Never Been Better (Deluxe Edition)</td>
            <td>Pop</td>
            <td>2014</td>
            <td>
                <a class="btn btn-xs btn-info" title="Visualizar" href="<?php echo $this->url('albuns', array("action" => "detalhes", "id" => 85,)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('albuns', array("action" => "editar", "id" => 85,)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('albuns', array("action" => "deletar", "id" => 85,)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
            </td>
        </tr>
        
        <tr>
            <td>4</td>
            <td>Alexandra Stan</td>
            <td>Unlocked (International Edition)</td>
            <td>Pop, R&B, Dance</td>
            <td>2014</td>
            <td>
                <a class="btn btn-xs btn-info" title="Visualizar" href="<?php echo $this->url('albuns', array("action" => "detalhes", "id" => 85,)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('albuns', array("action" => "editar", "id" => 85,)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('albuns', array("action" => "deletar", "id" => 85,)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
            </td>
        </tr>
        
        <tr>
            <td colspan="6"></td>
        </tr>
    </tbody>
</table>


<?php $this->headScript()->captureStart(); ?>
$(function(){
    // variável para conter a url deletar
    var url_deletar     = '<?php echo $this->url('albuns', array("action" => "deletar")); ?>' + '/';
 
    // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
    $("a[href*='" + url_deletar + "']").click(function (event) {
        // variável contendo o id referente ao botão clicado
        var contato_id  = $(this).attr('href').split(url_deletar).pop();
        // variável contendo mensagem da janela
        var mensagem = "Deseja realmente apagar o contato de ID " + contato_id + "?";
        // variável com resposta da mensagem colocada na janela
        var confirmacao = confirm(mensagem);
 
        // se a confirmação for false o fluxo é interrompido
        if (!confirmacao)
            // elimar o evendo do botão clicado
            event.preventDefault();
    });
});
<?php $this->headScript()->captureEnd(); ?>