<br><h1><label>Biblioteca de álbuns</label></h1>

<hr id="hr"/>

<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Novo Álbum          
        </div>
    </div>
    <?php
    // objeto form contato
    $formAlbum = $this->formAlbum;
    // preparar elementos do formulário
    $formAlbum->prepare();
    // configurar url formulário
    $formAlbum->setAttribute('action', $this->url('albuns', array('action' => 'adicionar')));
    ?>
    
    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formAlbum) ?>
        <div class="panel-body">
            <div class="form-group">
                <label for="inputArtista" class="col-lg-3 col-md-3 control-label">Artista:</label>
                <div class="col-lg-9 col-md-9">
                    <?php 
                    // renderiza html input
                    echo $this->formInput($formAlbum->get('artista'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formAlbum->get('artista'));
                    ?>
                </div>
            </div>
 
            <br><div class="form-group">
                <label for="inputTitulo" class="col-lg-3 col-md-3 control-label">Título do álbum:</label>
                <div class="col-lg-9  col-md-9">
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlbum->get('titulo'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formAlbum->get('titulo'));
                    ?>
                </div>
            </div>
 
            <br><div class="form-group">
                <label for="inputGenero" class="col-lg-3 col-md-3 control-label">Gênero:</label>
                <div class="col-lg-9  col-md-9">
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlbum->get('genero'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formAlbum->get('genero'));
                    ?>
                </div>
            </div>
            
            <br><div class="form-group">
                <label for="inputAno" class="col-lg-3 col-md-3 control-label">Ano:</label>
                <div class="col-lg-9  col-md-9">
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlbum->get('ano'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formAlbum->get('ano'));
                    ?>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-primary">Salvar álbum</button>
            <a href="<?php echo $this->url('albuns'); ?>" class="btn btn-default">Voltar</a>
        </div>
    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>﻿




