<br><h1><label>Biblioteca de álbuns</label></h1>

<hr id="hr"/>
<button id="btn-new" class="btn btn-primary" type="button">+ Novo álbum</button>

<form class="form-inline" id="float-r" role="form">
  <div class="form-group">
    <label for="inputEmail3" class="sr-only"></label>
    <input type="email" class="form-control" id="inputPassword2" placeholder="Busca...">
  </div>
  <button type="submit" class="btn btn-default">Procurar</button>
</form>

<table class="table">
    <thead><tr><th colspan="6"></th></tr></thead>
    <thead>
        <tr>
            <th>#</th>
            <th>Artista</th>
            <th>Álbum</th>
            <th>Gênero</th>
            <th>Ano</th>
            <th>Ação</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>1</td>
            <td>U2</td>
            <td>Songs of Innocense</td>
            <td>Rock</td>
            <td>2014</td>
            <td><a href="#">Editar</a> <a href="#">Deletar</a></td>
        </tr>

        <tr>
            <td>2</td>
            <td>David Guetta</td>
            <td>Listen (Deluxe Edition)</td>
            <td>Dance, House, Eletrônica</td>
            <td>2014</td>
            <td><a href="#">Editar</a> <a href="#">Deletar</a></td>
        </tr>

        <tr>
            <td>3</td>
            <td>Olly Murs</td>
            <td>Never Been Better (Deluxe Edition)</td>
            <td>Pop</td>
            <td>2014</td>
            <td><a href="#">Editar</a> <a href="#">Deletar</a></td>
        </tr>
        
        <tr>
            <td>4</td>
            <td>Alexandra Stan</td>
            <td>Unlocked (International Edition)</td>
            <td>Pop, R&B, Dance</td>
            <td>2014</td>
            <td><a href="#">Editar</a> <a href="#">Deletar</a></td>
        </tr>
        
        <tr>
            <td colspan="6"></td>
        </tr>
    </tbody>
</table>