<br><h1><label>Sobre o Projeto</label></h1>
<hr id="hr"/>
    <p class="lead">
        Esse projeto consiste em uma simples Biblioteca de Álbuns feita com 
        Zend Framework 2.
    </p>
 
    <h3>Ferramenta Utilizadas:</h3>
    
    <ul class="list-inline" style="font-size: 19px;">
        <li><span class="label label-primary">Zend Framework 2</span></li>
        <li><span class="label label-primary">ZFTool</span></li>
        <li><span class="label label-primary">Composer</span></li>
        <li><span class="label label-primary">PHP 5.5.15</span></li>
        <li><span class="label label-primary">Servidor Interno PHP 5.5.15</span></li>
        <li><span class="label label-primary">NetBeans 8</span></li>
        <li><span class="label label-primary">Git</span></li>
        <li><span class="label label-primary">GitHub</span></li>
        <li><span class="label label-primary">Boostrap Twitter 3</span></li>
        <li><span class="label label-primary">jQuery</span></li>
        <li><span class="label label-primary">MySql</span></li>
    </ul>
    
